// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/students": {
    params: {};
  };
  "/students/new": {
    params: {};
  };
  "/students/:id": {
    params: {
      "id": string;
    };
  };
  "/students/:id/edit": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/students" | "/students/new" | "/students/:id" | "/students/:id/edit";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/students.tsx": {
    id: "routes/students";
    page: "/students";
  };
  "routes/student-new.tsx": {
    id: "routes/student-new";
    page: "/students/new";
  };
  "routes/student-detail.tsx": {
    id: "routes/student-detail";
    page: "/students/:id";
  };
  "routes/student-edit.tsx": {
    id: "routes/student-edit";
    page: "/students/:id/edit";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/students": typeof import("./app/routes/students.tsx");
  "routes/student-new": typeof import("./app/routes/student-new.tsx");
  "routes/student-detail": typeof import("./app/routes/student-detail.tsx");
  "routes/student-edit": typeof import("./app/routes/student-edit.tsx");
};